version: 2

models:
  - name: base_data
    columns:
      - name: sepal_length
        tests:
          - not_null
      - name: sepal_width
        tests:
          - not_null
      - name: petal_length
        tests:
          - not_null
      - name: petal_width
        tests:
          - not_null
      - name: species
        tests:
          - not_null
          - accepted_values:
              values: ['setosa', 'versicolor', 'virginica']

    tests:
      - unique:
          column_name: "CONCAT(sepal_length, sepal_width, petal_length, petal_width)"
          where: "species = 'setosa'"